# Generated by Django 4.2.2 on 2023-06-28 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_villaversouser_confirm_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nbr_rooms', models.IntegerField(default=0)),
                ('nbr_people', models.IntegerField(default=0)),
                ('m2_house', models.IntegerField(default=0)),
                ('m2_garden', models.IntegerField(default=0)),
                ('pool', models.BooleanField(default=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('localisation', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.villaversouser')),
            ],
        ),
        migrations.CreateModel(
            name='ImageHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.house')),
            ],
        ),
    ]
