# Generated by Django 4.2.2 on 2023-06-28 13:06

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_house_imagehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehouse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
    ]
