# Generated by Django 4.2.2 on 2023-06-29 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_imagehouse_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Disponibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.house')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('house_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.villaversouser')),
                ('house_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.house')),
            ],
        ),
    ]
