# Generated by Django 4.2.2 on 2023-06-29 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_deal_nbr_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='house_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_client', to='api.house'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='house_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_receiver', to='api.house'),
        ),
    ]
